export const ROLES = {
  CREATOR: 'CREATOR',
  PARTICIPANT: 'PARTICIPANT'
}

export const PROGRESS = {
  WAITING_TO_BEGIN: 'WAITING_TO_BEGIN',
  WAITING_FOR_SEED: 'WAITING_FOR_SEED',
  WAITING_FOR_CONNECTIONS: 'WAITING_FOR_CONNECTIONS',
  WAITING_FOR_NEXT_ROUND: 'WAITING_FOR_NEXT_ROUND',
  GAME_ENDED: 'GAME_ENDED'
}

export default {
  ROLES,
  PROGRESS
}
